### ISSUE TITLE
More themes in this format

### ISSUE THREAD

**Issue by gagan-bansal** [jmblog/color-themes-for-highlightjs#3]
I am new to [highlightjs](https://highlightjs.org/) and [wintersmith](http://wintersmith.io/). In a new project of wintersmith default code highlight css classes are same (tomorrow) as in your project. 

I was able to replace **tomorrow** to **tomorrow-night** easily. 

There are many themes in highlight.js [demo](https://highlightjs.org/static/demo/). So how can I use those themes in wintersmith? or other way how can those themes be converted to the css classes as in your demo?

**Comment by jmblog** [comment]
@gagan-bansal Wow, I didn't know wintersmith uses the tomorrow theme in this project.

And I didn't know the highlightjs ~8.0.0 adds the `hljs-` prefix to all css classes. See [the release note](https://highlightjs.org/#news-79) for more details.

The wintersmith still uses [old styles](https://github.com/jnordberg/wintersmith/blob/718250eefdef08e9667650c350da0fb37c185936/src/plugins/markdown.coffee#L9), so if you want to use the themes packed into highlightjs in wintersmith, remove `hljs-` prefix from the class name.

The example:

```css
.hljs-comment {
  color: #8e908c;
}
```
↓
```css
.comment {
  color: #8e908c;
}
```

**Comment by gagan-bansal** [comment]
Thanks it worked very well for me.

**Comment by jmblog** [comment]
Great!
