### ISSUE TITLE
Links outdated

### ISSUE THREAD

**Issue by rugk** [jmblog/color-themes-for-highlightjs#6]
Most of your links in the comments of files in https://github.com/jmblog/color-themes-for-highlightjs/tree/gh-pages/css/themes are outdated and now return 404 errors.

**Comment by jmblog** [comment]
@rugk Thanks for your feedback. The domain of github pages has been changed... I'll fix them. Thanks.

**Comment by jmblog** [comment]
I'm really sorry for the late response. I've fixed the links.
