### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cubbi** [jmblog/color-themes-for-highlightjs#7]
Hey @jmblog,

I am trying to use it in our project, but I run into issue that usage license is not clear. Would it be possible to add License file to this repo, or clarify license in the README file?

**Comment by jmblog** [comment]
Hi @cubbi,

Thanks for pointing that. I've added the [LICENSE.md](https://github.com/jmblog/color-themes-for-highlightjs/blob/7ff6ccfa6e17ab7adb83217e1f699f167e9c97f5/LICENSE.md) file. Please check it.
