### ISSUE TITLE
Links still outdated

### ISSUE THREAD

**Issue by nyanpasu64** [jmblog/color-themes-for-highlightjs#9]
Pages like https://jmblog.github.io/color-themes-for-highlightjs/tomorrow-night-bright/ don't load properly, because your source code links to jmblog.github.com, which is no longer a working redirect for *.github.io.

**Comment by jmblog** [comment]
@nyanpasu64 Thank you for reporting. I'll fix it soon.

**Comment by jmblog** [comment]
@nyanpasu64 I've fixed the URLs. Please tell me if you find some problems left.

**Comment by jmblog** [comment]
@nyanpasu64 P.S. The themes included in this repository don't support the latest version of highlight.js. I recommend using a wide variety of themes in the official repository.

https://highlightjs.org/static/demo/

**Comment by nyanpasu64** [comment]
It seems to work now. I don't know if there's anything else broken. Maybe you could add a semi-prominent link to the official repository on all pages in your site.
